//
// Created by os on 2/11/23.
//

#ifndef OS1_VEZBE07_RISCV_CONTEXT_SWITCH_2_INTERRUPT_USERMAIN_HPP
#define OS1_VEZBE07_RISCV_CONTEXT_SWITCH_2_INTERRUPT_USERMAIN_HPP

void userMain();

#endif //OS1_VEZBE07_RISCV_CONTEXT_SWITCH_2_INTERRUPT_USERMAIN_HPP
